### PR TITLE
#69 - MyBB 1.8.23 - global.lang.php

### PR DESCRIPTION
**Pull request by Eldenroot**
Part of #69

### CODE REVIEW

**Review by BKPepe — CHANGES_REQUESTED** [review]
This looks good as it is. But please squash your commits before merging and in the single commit change the commit subject to something appropriate.

**Comment by Eldenroot** [comment]
@BKPepe - Unfortunately not possible right now, I will update all subjects, add mentions to base issue. Next time.

MyBB 1.8.23 had a lot of changes and we havent released compatible version over 10 months?

**Comment by BKPepe** [comment]
I am not using MyBB so much these days. It's unfortunate. 
And I am trying to catch with all the things which I should need to do.

**Comment by Eldenroot** [comment]
@BKPepe - no problem buddy, same here. I am just trying all the things and make MyBB Czech package up to date 👍

**Pull request merged**
